CREATE USER 'repl_2'@'%' IDENTIFIED BY 'pass';
GRANT REPLICATION SLAVE ON *.* TO 'repl_2'@'%';

CHANGE MASTER TO 
MASTER_HOST = 'master-1', 
MASTER_USER ='repl_1', 
MASTER_PASSWORD = 'pass',
GET_MASTER_PUBLIC_KEY=1;

START SLAVE;