CREATE USER 'repl_1'@'%' IDENTIFIED BY 'pass';
GRANT REPLICATION SLAVE ON *.* TO 'repl_1'@'%';

CHANGE MASTER TO 
MASTER_HOST = 'master-2', 
MASTER_USER ='repl_2', 
MASTER_PASSWORD = 'pass',
GET_MASTER_PUBLIC_KEY=1;

START SLAVE;